spring:
    datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:testdb
      username: sa
      password: '{cipher}9d0b5a1f5a3260f03ad6833bd5c3e32f48dce80331f455101315c8fc583dfda5'

token:
  expiration_time: 86400000
  secret: abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz

gateway:
  ip: 192.168.0.2

order_service:
  url: http://localhost:8888/order-service/%s/orders